map:
  layers:
    - id: 1
      name: district A
      edges:
        - dst: 6
          val: 10
    - id: 2
      name: street A
      parent: 1
      edges:
        - dst: 3
          val: 1
    - id: 3
      name: street B
      parent: 1
      edges:
        - dst: 2
          val: 1
        - dst: 4
          val: 3
    - id: 4
      name: street C
      parent: 1
      edges:
        - dst: 3
          val: 3
        - dst: 5
          val: 1
    - id: 5
      name: house A
      parent: 4
      edges:
        - dst: 4
          val: 1
    - id: 6
      name: district B
